# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06cb520c257ac82a9d9550ec2240e4a92caf3daf169e7e4633fa231fbc96ef41777ee1059b829a3e3af0069696bcf9e650641d2cdb33c688afb24a91abc46974

test:
  secret_key_base: 018d69ef1b4eb7ebb9e4a5ecee79cb7d53c9e04c5709ee9b7d56e4179ceb7bd9d019dcd348510bf7bf48db991cc990e93123e3ee1ff81b66a84bf77b9980b255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
